# Generated by Django 4.2.1 on 2024-03-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="number_of_comments",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
