# Generated by Django 4.2.1 on 2024-03-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_user_commment_comment_user_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="number_of_comments",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rate",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
