# Generated by Django 4.2.1 on 2024-03-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_number_of_comments_alter_product_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rate",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
